name: tests

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:
  ci:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: booking_test
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --name ci-mysql
          --health-cmd="mysqladmin ping -h 127.0.0.1 -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl, pdo_mysql
          coverage: none
          tools: composer:v2

      - name: Wait for MySQL
        run: |
          for i in {1..60}; do
            mysqladmin ping -h 127.0.0.1 -proot && break
            sleep 2
          done

      - name: Install Composer deps
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Prepare env for CI
        run: |
          cp .env.ci .env
          php artisan key:generate
          php artisan config:clear
          php artisan cache:clear
          # на всякий случай
          mysql -h 127.0.0.1 -uroot -proot -e "CREATE DATABASE IF NOT EXISTS booking_test CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"

      - name: Run migrations + seed
        run: php artisan migrate --no-interaction --seed

      - name: Run tests (Pest or PHPUnit)
        run: |
          if [ -f ./vendor/bin/pest ]; then
            ./vendor/bin/pest
          else
            php artisan test
          fi
